[global]
# Global configuration for Streamlit app

# Show error details in development
developmentMode = false

[server]
# Server configuration
port = 8501
headless = false

# Enable CORS for API calls
enableCORS = true
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false

[theme]
# Theme configuration for the app
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# Client configuration
toolbarMode = "minimal"
